apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ${app.name}
  labels:
    app: ${app.name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${app.name}
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
      labels:
        app: ${app.name}
    spec:
      serviceAccountName: ${app.name}
      containers:
        - name: ${app.name}
          image: ${artifact.image}:${artifact.tag}
          ports:
            - containerPort: 9002
          env:
            %{ for k,v in entrypoint.env }
            - name: ${k}
              value: "${v}"
            %{ endfor }
            - name: PORT
              value: "9002"
            - name: WAYPOINT_LOG_LEVEL
              value: "TRACE"
